/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;

/**
 *
 * @author Iván Aguilar
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jComboBoxOperaciones = new javax.swing.JComboBox<>();
        jButtonCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabelTitulo.setFont(new java.awt.Font("Malayalam MN", 2, 24)); // NOI18N
        jLabelTitulo.setText("Calculadora de Matrices");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 310));
        setUndecorated(true);
        setSize(new java.awt.Dimension(540, 310));
        getContentPane().setLayout(null);

        jLabelTitulo1.setFont(new java.awt.Font("Malayalam MN", 2, 24)); // NOI18N
        jLabelTitulo1.setText("Calculadora de Matrices");
        getContentPane().add(jLabelTitulo1);
        jLabelTitulo1.setBounds(130, 80, 258, 32);

        jComboBoxOperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una operación", "Suma de matrices", "Multiplicación por un escalar", "Multiplicación de matrices", "Obtención de la transpuesta de una matriz", "Obtención de la inversa de una matriz (Gauss)", "Sistema de ecuaciones por Gauss-Jordan", "Encontrar la determinante de una matriz " }));
        jComboBoxOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOperacionesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxOperaciones);
        jComboBoxOperaciones.setBounds(110, 160, 310, 20);

        jButtonCerrar.setBackground(new java.awt.Color(255, 102, 102));
        jButtonCerrar.setText("Cerrar");
        getContentPane().add(jButtonCerrar);
        jButtonCerrar.setBounds(220, 230, 73, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/white-wood-texture-abstract-16498.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 310);

        setSize(new java.awt.Dimension(540, 310));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOperacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOperacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    public JComboBox<String> getjComboBoxOperaciones() {
        return jComboBoxOperaciones;
    }

    public void setjComboBoxOperaciones(JComboBox<String> jComboBoxOperaciones) {
        this.jComboBoxOperaciones = jComboBoxOperaciones;
    }

    public JButton getjButtonCerrar() {
        return jButtonCerrar;
    }

    public void setjButtonCerrar(JButton jButtonCerrar) {
        this.jButtonCerrar = jButtonCerrar;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JComboBox<String> jComboBoxOperaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    // End of variables declaration//GEN-END:variables
}
